// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// r_getword
CharacterVector r_getword(SEXP test, SEXP min_l, SEXP max_l);
RcppExport SEXP Rgetword_r_getword(SEXP testSEXP, SEXP min_lSEXP, SEXP max_lSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type test(testSEXP );
        Rcpp::traits::input_parameter< SEXP >::type min_l(min_lSEXP );
        Rcpp::traits::input_parameter< SEXP >::type max_l(max_lSEXP );
        CharacterVector __result = r_getword(test, min_l, max_l);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
