# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_getword <- function(test, min_l, max_l) {
    .Call('Rgetword_r_getword', PACKAGE = 'Rgetword', test, min_l, max_l)
}

